[book]
authors = ["Nikita Ramses Abdoelrahman"]
language = "en"
multilingual = false
src = "src"
title = "Space Frontiers Docs"

[output.html]
git-repository-url = "https://github.com/starwolves/space"
